### ISSUE TITLE
tensorflow > 2.14 no longer supports tf.keras.__version__, causes error in notebook

### ISSUE THREAD

**Issue by atmelino** [jeffheaton/t81_558_deep_learning#175]
I installed tensorflow per your instructions, and got version 2.15 with Ubuntu 22.04 in February 2024.
the notebook at
https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-march-2023.ipynb
gives the error
AttributeError: module 'tensorflow.keras' has no attribute '__version__'
according to 
https://stackoverflow.com/questions/46086030/how-to-check-which-version-of-keras-is-installed
this attribute no longer exists in tensorflow version > 2.13

I was able to resolve the issue by running
`conda install tensorflow=2.1.0`

Please note, I do not have the time availability to help with individual installation requests. If you've noticed something that needs to be changed in the installation instructions, please report what you think needs to be changed. Generally I rerun my installation instructions once a semester and make any adjustments needed at that point.

**Describe the bug**
A clear and concise description of what the bug is.  If you have a general programming question, [Stack Overflow](https://stackoverflow.com/) is a better forum.  Please only add issues specifically related to a problem with the code in this repository. 

**Expected behavior**

**Which Notebook Contains this Issue**
Please let me know which notebook contains the code for the issue you are reporting. (e.g. https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_01_1_overview.ipynb)

**Comment by jeffheaton** [comment]
I have not been able to reproduce this, perhaps a temporary change?

```
import tensorflow as tf
print(tf.__version__)
print(tf.keras.__version__)
```

Gives me

```
2.17.1
3.5.0
```

**Comment by atmelino** [comment]
Confirmed:

It worked with tensorflow version 2.10, not with 2.15, but then again with 2.17

Results:

### 2.10
conda list
```
tensorflow                2.10.0          cuda112py310he87a039_0    conda-forge
```
Your code output
```
2.10.0
2.10.0
```

### 2.15
conda list
```
tensorflow                2.15.0          cuda120py310h9360858_3    conda-forge
```
Your code output
```
AttributeError: module 'keras.api._v2.keras' has no attribute '__version__
```

### 2.17
conda list
```
tensorflow                2.17.0          cuda120py310heb3ae67_203    conda-forge
```
Your code output
```
2.17.0
3.8.0
```
